### ISSUE TITLE
Browser support: why is this library compiled to ES6?

### ISSUE THREAD

**Issue by silvenon** [date-fns/date-fns-upgrade#6]
It seems like an unnecessary cutoff in browser support (e.g. IE doesn't support arrow functions).

**Comment by silvenon** [comment]
ES5 fork: [@radek-palisa/date-fns-upgrade](https://www.npmjs.com/package/@radek-palisa/date-fns-upgrade)

**Comment by dkozickis** [comment]
Hi @silvenon , we're happy to accept a PR to this repo if you feel like it :)

**Comment by dkozickis** [comment]
Thank you @silvenon, released as v1.0.3 :)
